package com.lb.service;

import java.io.File;
import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.stereotype.Service;

import com.lb.entity.CitizenReports;
import com.lb.repo.CitizenRepo;
import com.lb.search.SearchRequest;
import com.lb.util.EmailUtils;
import com.lb.util.ExcelGenerator;
import com.lb.util.PdfGenerator;

import jakarta.servlet.http.HttpServletResponse;
import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class CitizenServiceImpl implements CitizenService {

	private final CitizenRepo citizenRepo;

	private final ExcelGenerator excelGenerator;

	private final PdfGenerator pdfGenerator;

	private final EmailUtils emailUtils;

	@Override
	public List<String> getPlanStatus() {
		return citizenRepo.getCitizenStatus();
	}

	@Override
	public List<String> getPlanName() {
		return citizenRepo.getCitizenName();
	}

	@Override
	public List<CitizenReports> Search(SearchRequest request) {
		CitizenReports entity = new CitizenReports();
//		BeanUtils.copyProperties(search, report);
		if (null != request.getPlanName() && !"".equals(request.getPlanName())) {
			entity.setPlanName(request.getPlanName());
		}
		if (null != request.getCitizenStatus() && !"".equals(request.getCitizenStatus())) {
			entity.setCitizenStatus(request.getCitizenStatus());
		}
		if (null != request.getGender() && !"".equals(request.getGender())) {
			entity.setGender(request.getGender());
		}
		if (null != request.getStartDate() && !"".equals(request.getStartDate())) {

			entity.setStartDate(request.getStartDate());
		}
		if (null != request.getEndDate() && !"".equals(request.getEndDate())) {

			entity.setEndDate(request.getEndDate());
		}
		return citizenRepo.findAll(Example.of(entity));
	}

	@Override
	public boolean exportExcel(HttpServletResponse response) throws Exception {
		File f = new File("Plans.xls");
		List<CitizenReports> list = citizenRepo.findAll();
		excelGenerator.excelGenerator(response, list, f);

		String msg = "Citizen Reports – Excel Export";

		String text = "<h2>Citizen Reports – Excel File</h2>" + "<p>Hello,</p>"
				+ "<p>Please find the attached <b>Excel report</b> generated from the Citizen Reports Application.</p>"
				+ "<p>The file contains dynamically filtered citizen plan data based on system records.</p>" + "<br>"
				+ "<p><b>Generated By:</b> Citizen Reports App</p>"
				+ "<p><b>Technology:</b> Spring Boot | Apache POI</p>" + "<br>"
				+ "<p>Regards,<br>Pinku Prusty<br>Java Developer</p>";

		String to = "pinkunaprusty2002@gmail.com";

		emailUtils.mailsender(msg, text, to, f);
		f.delete();
		return true;
	}

	@Override
	public boolean exportPdf(HttpServletResponse response) throws Exception {

		File f = new File("Plans.pdf");
		List<CitizenReports> list = citizenRepo.findAll();
		pdfGenerator.pdfGenerator(response, list, f);

		String msg = "Citizen Reports – PDF Export";

		String text = "<h2>Citizen Reports – PDF File</h2>" + "<p>Hello,</p>"
				+ "<p>Please find the attached <b>PDF report</b> generated from the Citizen Reports Application.</p>"
				+ "<p>This document includes citizen plan details exported directly from the database.</p>" + "<br>"
				+ "<p><b>Generated By:</b> Citizen Reports App</p>" + "<p><b>Technology:</b> Spring Boot | OpenPDF</p>"
				+ "<br>" + "<p>Regards,<br>Pinku Prusty<br>Java Developer</p>";

		String to = "pinkunaprusty2002@gmail.com";

		emailUtils.mailsender(msg, text, to, f);
		f.delete();
		return true;
	}

}
